language: node_js
node_js:
  - 10
services: mongodb
before_script: mkdir uploads
cache:
  directories:
    - "node_modules"
script:
  - npm test
  - jest -i --coverage --forceExit && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
